mongodb_uri: "mongodb+srv://${username}:${password}@${host}/alist_sync?retryWrites=true&w=majority&appName=A1"
cache_dir: ./.cache
daemon: false

alist_servers:
  - url: http://localhost:5244/
    username: "admin"
    password: "admin"
    verify_ssl: false
  - url: http://localhost:5245/
    username: "admin"
    password: "admin"


sync_groups:
  - name: "sync1"
    # 同步类型，一共5种：
    # 1 copy:如果目标目录中已经存在该文件，则跳过
    #        忽略存在与目标目录中但不存在于源目录中的文件
    # 2 mirror: 如果目标目录中已经存在该文件，则跳过
    #           删除存在于目录目录但不存在于源目录中的文件
    # 3 sync: 如果目标目录中已经存在该文件，则跳过
    #         删除存在于目录目录但不存在于源目录中的文件
    # 4 sync-incr: 基于文件的修改时间，只同步源目录中修改时间晚于目标目录的文件
    type: "copy"
    group:
      - "http://localhost:5244/test1"
      - "http://localhost:5245/test2"

